= Fazit und Ausblick

== Fazit

Die vorliegende Arbeit untersucht eine Forschungsfrage, die aus zwei Teilproblemen öffentlicher Kiosk-Systeme entsteht: einerseits dem bewussten Verzicht auf Login-Mechanismen @porcheron2018voice[S.~3], andererseits dem fehlenden persistenten Gedächtnis großer Sprachmodelle über Sitzungsgrenzen hinweg @zhang2018persona[S.~2388]:

#rect(width: 100%, inset: (x: 12pt, y: 10pt), radius: 4pt, stroke: 0.5pt)[
  _„Wie kann ein öffentlicher KI-Assistent durch kamerabasierte Gesichtserkennung mittels Deep-Learning-Embeddings wiederkehrende Nutzer identifizieren und eine sitzungsübergreifend personalisierte Konversationserfahrung bereitstellen?"_
]

Die Frage lässt sich auf Basis des entwickelten und evaluierten Prototyps positiv beantworten: Ein öffentlicher KI-Assistent kann wiederkehrende Nutzer durch kamerabasierte Gesichtserkennung mit Deep-Learning-Embeddings zuverlässig identifizieren --- die in der Evaluation belegte Erkennungsleistung des verwendeten ArcFace-Verfahrens @deng2019arcface[S.~3] in Verbindung mit Retrieval-Augmented Generation als Mechanismus der Kontextpersistenz @lewis2020rag[S.~2] trägt diese Antwort. Die entwickelte Systemarchitektur demonstriert dies entlang drei technischer Kernkomponenten.

Die Personenerkennung des entwickelten Systems verbindet einen ressourcenschonenden Frontaldetektor @bazarevsky2019blazeface[S.~2] (BlazeFace, vgl. Kap.~4.1) mit einem zweistufigen Tracking (Positions-Prä-Filter, dann ArcFace-Matching, vgl. Kap.~5.2), sodass Detektionen auch bei Kopfdrehungen jenseits der in Kap.~7 berichteten 30°-Winkelschwelle stabil einer Person zugeordnet werden, ohne jeden Frame mit der rechenintensiven Embedding-Berechnung zu belasten. Die biometrische Identifikation über InsightFace buffalo\_l (ArcFace ResNet50, ONNX Runtime) liegt im LFW-Benchmark über der FaceNet-Baseline (vgl. Kap.~7.1) und arbeitet bei Echtzeit-tauglicher Inferenzlatenz (vgl. Kap.~7.2); die Wahl gegen die Alternativen ist in Kap.~3.3 begründet, theoretisch stützt sich der Genauigkeitsvorsprung auf die angulare Margin-Loss-Funktion (vgl. Kap.~2.2.2) @deng2019arcface[S.~3] der zugrunde liegenden ArcFace-Architektur. Das sitzungsübergreifende Gedächtnis (Fakt-Extraktion und RAG-Retrieval, vgl. Kap.~6.1/6.2) löst das in Kap.~2.3.1 beschriebene Kontextfenster-Problem ohne Speicherung roher Gesprächshistorien @lewis2020rag[S.~2]. Die End-to-End-Latenz vom ersten Kamerabild bis zum personalisierten Greeting liegt im einstelligen Sekundenbereich (eigene Messung, vgl. Kap.~7.2) --- akzeptabel für den Kiosk-Kontext, in dem eine interaktionswillige Person typischerweise länger als 10 s vor dem Bildschirm steht.

Das Gesamtsystem zeigt, dass biometrische Personalisierung in einem öffentlichen KI-Assistenten ohne Login technisch realisierbar ist. Im entwickelten System verbinden sich Embedding-basierte Identifikation @deng2019arcface[S.~3], eine zustandsbehaftete Anwesenheitserkennung und ein semantisches Gedächtnis auf Basis von Retrieval-Augmented Generation @lewis2020rag[S.~2] zu einem kohärenten, produktionsnah implementierbaren System, das die in Kap.~1.1 beschriebene technische Einschränkung der Personalisierungsqualität schließt --- eine Einschränkung, die für öffentlich zugängliche Sprach- und Konversationssysteme strukturell ist @porcheron2018voice[S.~3].

== Ausblick

Obwohl der entwickelte Prototyp die Forschungsfrage beantwortet, eröffnet er mehrere Weiterentwicklungsrichtungen, die über den Scope dieser Arbeit hinausgehen --- insbesondere auf andere Kontexte, in denen öffentlich zugängliche Systeme bewusst ohne Login betrieben werden @porcheron2018voice[S.~4] und passive biometrische Identifikation deshalb das einzig praktikable Verfahren zur Personenidentifikation darstellt @jain2011biometrics[S.~12].

Die unmittelbar interessanteste Weiterentwicklung ist die Domänenübertragung: Das entwickelte System ist prinzipiell nicht auf den SAP-Kiosk-Kontext beschränkt, sondern auf alle Settings übertragbar, in denen die Nutzer bekannt sind, aber keine explizite Login-Infrastruktur existiert @porcheron2018voice[S.~4]. Denkbare Anwendungsfelder reichen von der Pflege (Begrüßung beim Betreten eines Patientenzimmers mit Vitaldaten und Pflegeplan, ohne Geräteentsperrung) über den Bildungsbereich (adaptive Lernsysteme, die Lernhistorie und Schwächen ohne Login laden) bis hin zum Retail (stationäre Beratungssysteme, die Stammkunden erkennen und proaktiv auf frühere Präferenzen eingehen).

Die zweite Entwicklungsrichtung betrifft die datenschutzrechtliche Konsolidierung. Der Prototyp wurde unter Laborbedingungen entwickelt; ein DSGVO-konformer Produktiveinsatz erfordert darüber hinausgehende Maßnahmen: explizite Einwilligungsmechanismen, ein transparentes Opt-out-Verfahren mit garantierter Datenlöschung, technische Nachvollziehbarkeit der gespeicherten Embeddings (d.~h. die Möglichkeit, ein gespeichertes Embedding einer Person eindeutig zuzuordnen und zu löschen, vgl. Kap.~3.5) und eine Datenhaltung, die den expliziten Anforderungen des Verordnungstextes an die „Verarbeitung biometrischer Daten zur eindeutigen Identifizierung einer natürlichen Person" [DSGVO 2016, Art.~9 Abs.~1] genügt; Gesichtsembeddings fallen dabei nach geltender Auslegung als biometrische Daten besonderer Kategorie unter Art.~9 @hogenhout2025biometricprivacy[S.~2--4]. Biometrische Identifikation im öffentlichen Raum unterliegt erhöhten Anforderungen, die über die rein technische Umsetzbarkeit hinausgehen und regulatorische sowie gesellschaftliche Abwägungen erfordern @jain2011biometrics[S.~297].

Die dritte Richtung ist die technische Reifung des Systems: Die in Kap.~7 identifizierten Einschränkungen bilden einen konkreten Forschungsplan für eine vertiefte Evaluation. Eine kontrollierte Studie mit standardisierten Beleuchtungsverhältnissen und einer hinreichend großen Probandengruppe würde die in dieser Arbeit auf Benchmark-Werten basierenden Genauigkeitsaussagen empirisch absichern @schroff2015facenet[S.~1] und die Langzeitstabilität des Embedding-Gedächtnisses gegen die in Kap.~7.3 diskutierte Drift-Problematik validieren --- insbesondere die Frage, ob die im Trainingskontext geltende Margin-getriebene Diskriminierungsfähigkeit @deng2019arcface[S.~3] auch unter wiederholten Begegnungen über Wochen und Monate stabil bleibt.
