// ---- Abbreviations ---- //
// Each entry: ("SHORT", "Full description")
#let abbreviations = (
  ("ANN",    "Approximate Nearest Neighbor"),
  ("API",    "Application Programming Interface"),
  ("CNN",    "Convolutional Neural Network"),
  ("CPU",    "Central Processing Unit"),
  ("DSGVO",  "Datenschutz-Grundverordnung"),
  ("EMA",    "Exponential Moving Average"),
  ("GPU",    "Graphics Processing Unit"),
  ("HNSW",  "Hierarchical Navigable Small World"),
  ("HTTP",   "Hypertext Transfer Protocol"),
  ("K8s",    "Kubernetes"),
  ("KI",     "Künstliche Intelligenz"),
  ("LFW",    "Labeled Faces in the Wild"),
  ("LLM",    "Large Language Model"),
  ("MCP",    "Model Context Protocol"),
  ("ONNX",   "Open Neural Network Exchange"),
  ("RAG",    "Retrieval-Augmented Generation"),
  ("SAP",    "Systeme, Anwendungen und Produkte"),
  ("SIMD",   "Single Instruction, Multiple Data"),
  ("STT",    "Speech-to-Text"),
  ("TTS",    "Text-to-Speech"),
  ("UX",     "User Experience"),
  ("VAD",    "Voice Activity Detection"),
  ("VLM",    "Vision-Language-Modell"),
  ("WebSocket", "WebSocket-Protokoll (RFC 6455)"),
)
